### ISSUE TITLE
Paper/Explanation to invariant.py?

### ISSUE THREAD

**Issue by OlBeXTR** [TSchattschneider/Color-Constancy#1]
Hello,

is there a paper or kind of explanation for the file 'invariant.py'? Especially I like to understand the function rgb2ii. What is the the scientific reason you calculate ii_image the way you do?

Greetings
OlBeXTR

**Comment by TSchattschneider** [comment]
It‘s based on the paper „Illumination Invariant Imaging: Applications in Robust Vision-based Localisation, Mapping and Classification for Autonomous Vehicles” by Will Maddern et. al, so you will find all the scientific motivation in there.

I played around with this implementation of eq. 5 from the paper for object detection under varying lighting conditions. It was meant to be used at a RoboCup competition.
